version: '3.9'
services:
  postgres:
    container_name: Final-project
    image: postgres:15.1-alpine3.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data


  adminer:
    image: adminer
    restart: always
    ports:
      - "5050:8080"
    depends_on:
      - postgres

volumes:
  pgdata: